package com.prod.persistence;

public enum CollectionNames {

    //Step 5
    AVAILABLE_TIME_FACILITY_COLLECTION,

    //Step 6
    AVAILABLE_TIME_STAFF_COLLECTION,

    //Step 1
    ORG_SCOPE_COLLECTION,
    ORG_DEPARTMENT_COLLECTION,

    //Step 2
    DEPARTMENT_PROCEDURE_COUNT_COLLECTION,
    TOTAL_DEPARTMENT_TIME_COLLECTION,

    //Step 4
    THROUGHPUT_GOALS_COLLECTION,
    DEPARTMENT_OPERATIONS_DAYS_COLLECTION,
    STAFF_REQUIREMENT_COLLECTION,

    //Step 7
    PROCESS_TIME_COLLECTION;

}
